beccaria_fr1_1_1766 = {'fréquens': 'fréquent',  'tems': 'temps',  '[*': '[',  'mouvemens': 'mouvement',  'chargeroient': 'chargeront',  'avois': 'avais',  'connoissent': 'connaissent',  'par-tout': 'partout',  'diviseroient': 'diviseraient',  'déclamations': 'déclarations',  'seroit': 'serait',  'faudroit': 'faudrait',  'étoit': 'était',  'dirois': 'dirais',  'secrettement': 'secrètement',  'seroient': 'seraient',  'barrieres': 'barrières',  'tourmens': 'tourments',  'sévérement': 'sévèrement',  'préféreroit-elle': 'préférerait-elle',  'foiblesse': 'faiblesse',  'chose)': 'chose )',  'affoiblir': 'affaiblir'}

beccaria_fr2_1_1773 = {'paroîtra': 'paraîtra',  'croiroit': 'croirait',  'péu': 'peu',  'ayent': 'ayant',  'celleslà': 'celles-là',  'affoiblies': 'affaiblies',  'plûpart': 'plupart',  'paroissent': 'paraissent',  'gouvervement': 'gouvernement',  'récens': 'récent',  'fréquens': 'fréquent',  'tems': 'temps',  'toutà-fait': 'tout-à-fait',  'mouvemens': 'mouvement',  'pouvoit': 'pouvait',  'fource': 'source',  'différe': 'diffère',  'delits': 'délits',  'sur-tout': 'surtout',  'pénetré': 'pénétré',  'parlois': 'parlais',  'montrerois': 'montrerais',  'sociéré': 'société',  'prévenués': 'prévenus',  'climat)': 'climat )',  'connoit': 'connait',  'non-seulement': 'non seulement',  'dàcharger': 'décharger',  'efprit': 'esprit',  'foibles': 'faibles',  'desirs': 'désirs',  'delit': 'délit',  'foible': 'faible',  'desirer': 'désirer',  'sévérement': 'sévèrement',  'plaifirs': 'plaisirs',  'etfet': 'effet',  'guères': 'guère',  'foiblesse': 'faiblesse',  'céde': 'cédé',  'seroit': 'serait',  'sauroit': 'saurait',  'certe': 'cette',  'affoiblir': 'affaiblir'}

beccaria_fr2_2_1782 = {'paroîtra': 'paraîtra',  'croiroit': 'croirait',  'p1us': 'plus',  'affoiblies': 'affaiblies',  'paroissent': 'paraissent',  'fréquens': 'fréquent',  'tems': 'temps',  'adultere': 'adultère',  'récens': 'récent',  'nnocence': 'innocence',  'pouvoit': 'pouvait',  ')ne': ') ne',  'differe': 'diffère',  'sur-tout': 'surtout',  'sémi-preuves': 'semi-preuves',  'mouvemens': 'mouvement',  'fource': 'source',  'montrerois': 'montrerais',  'parlois': 'parlais',  'préuve': 'preuve',  '[on': '[ on',  'connoît': 'connaît',  'foibles': 'faibles',  'moralistes': 'moraliste',  'foible': 'faible',  'desirs': 'désirs',  'barrieres': 'barrières',  'aisement': 'aisément',  'séveres': 'sévères',  'sévérement': 'sévèrement',  'guere': 'guère',  'foiblesse': 'faiblesse',  'presqu': 'presque',  'seroit': 'serait',  'éleve': 'élève',  'sauroit': 'saurait',  'affoiblir': 'affaiblir'}

beccaria_fr2_3_1784 = {'paroîtra': 'paraîtra',  'croiroit': 'croirait',  'ayent': 'ayant',  'celleslà': 'celles-là',  'affoiblies': 'affaiblies',  'paroissent': 'paraissent',  'récens': 'récent',  'fréquens': 'fréquent',  'pouvoit': 'pouvait',  'sémi-preuves': 'semi-preuves',  'instruétion': 'instruction',  '(crimes': '( crimes',  'tems': 'temps',  'sur-tout': 'surtout',  'prouver)': 'prouver )',  'toutà-fait': 'tout-à-fait',  'mouvemens': 'mouvement',  'lesquelle': 'lesquelles',  'montrerois': 'montrerais',  'parlois': 'parlais',  '(dans': '( dans',  'climat)': 'climat )',  'connoît': 'connaît',  'foibles': 'faibles',  'delirs': 'désirs',  'foible': 'faible',  'desirer': 'désirer',  'foiblesse': 'faiblesse',  'sesoit': 'serait',  'sauroit': 'saurait',  'affoiblir': 'affaiblir'}

beccaria_fr2_4_1794 = {'paroîtra': 'paraîtra',  'croiroit': 'croirait',  'ayent': 'ayant',  'légistateurs': 'législateurs',  'celleslà': 'celles-là',  'gouvernementet': 'gouvernement et',  'affoiblies': 'affaiblies',  'adiministration': 'administration',  'proprés': 'propres',  'paroissent': 'paraissent',  'plûpart': 'plupart',  'passious': 'passions',  'mouvemens': 'mouvement',  'récens': 'récent',  'dilficulté': 'difficulté',  'fréquens': 'fréquent',  'multiptier': 'multiplier',  'pouvoit': 'pouvait',  'inpunité': 'impunité',  'sur-tout': 'surtout',  'diférences': 'différences',  'bcsoins': 'besoins',  'montrerois': 'montrerais',  'connoît': 'connaît',  'parlois': 'parlais',  'foibles': 'faibles',  'inpuni': 'impuni',  'puissaice': 'puissance',  'preceptes': 'préceptes',  'desirs': 'désirs',  'foible': 'faible',  'satiété': 'société',  'guères': 'guère',  'foiblesse': 'faiblesse',  'seroit': 'serait',  'sauroit': 'saurait',  'affoiblir': 'affaiblir'}

beccaria_fr2_5_1797Ch = {'ayent': 'ayant',  'àla-fois': 'à la fois',  'affaiblies': 'affaiblies',  'récens': 'récent',  'fréquens': 'fréquent',  'à-la-fois': 'à la fois',  'ditficultés': 'difficultés',  'sémi-preuves': 'semi-preuves',  'soupconne': 'soupçonne',  'sur-tout': 'surtout',  'prouver)': 'prouver )',  'même-tems': 'même temps',  'mouvemens': 'mouvement',  '(dans': '( dans',  'climat)': 'climat )',  'desirs': 'désirs',  'secrette': 'secrète',  'soupcon': 'soupçon',  'desirer': 'désirer',  'satiété': 'société'}

beccaria_fr1_2_1797Mo = {'sociélé': 'société',  'fréquens': 'fréquent',  'même-temps': 'même temps',  'modife': 'modifie',  '[*': '[',  'mouvemens': 'mouvement',  'auteur]': 'auteur ]',  'avois': 'avais',  'dirois': 'dirais',  'luimême': 'lui-même',  'chargeroient': 'chargeront',  'connoissent': 'connaissent',  'diviseroient': 'diviseraient',  'seroit': 'serait',  'faudroit': 'faudrait',  'étoit': 'était',  'seroient': 'seraient',  'tourmens': 'tourments',  'cormmence': 'commence',  'foiblesse': 'faiblesse',  'préféreroit': 'préférerait',  'afioiblir': 'affaiblir',  'prétens': 'prétend'}